# Generated by Django 4.2.5 on 2023-11-08 15:05

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="testdb",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("image_path", models.CharField(max_length=255)),
                ("success", models.CharField(max_length=255)),
                ("message", models.CharField(max_length=255)),
                ("returnclass", models.IntegerField()),
                ("confidence", models.DecimalField(decimal_places=4, max_digits=5)),
                ("request_timestamp", models.IntegerField()),
                ("response_timestamp", models.IntegerField()),
            ],
        ),
    ]
